// <auto-generated />
using System;
using DemoCICD.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DemoCICD.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250209100000_SeedRbacData")]
    partial class SeedRbacData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder) { }
    }
}
